### ISSUE TITLE
Execute Copy task on multiple targets

### ISSUE THREAD

**Issue by amezng** [terazyte/teraflow#1]
Currently if we want copy same set of files to multiple targets/servers, we have to duplicate the copy task with different targets.
Following is an example of how to run copy task on multiple targets
```
cp: 
  from: 
  targets: 
    - t1
    - t2
```
